### ISSUE TITLE
Some questions related to the code running in HPA

### ISSUE THREAD

**Issue by HelloWorldLTY** [RonenTalmonLab/HyperbolicProcrustesAnalysis#2]
Hello, sorry to disturb you again, I am Tianyu. I tried to get the embeddings value using facebook team's method but I still found some problem to run your hpa. The error comes from this code:
<img width="885" alt="26ef8ec16c27b6283d66afa14845528" src="https://user-images.githubusercontent.com/43333475/146450184-a58ae621-9395-434f-a67a-eac803397eaf.png">
I will receive an error saying that the Lorentz inner product method cannot handle with data whose types are not torch.tensor. I think the problem is caused by tmp, which is a int. Therefore, I wonder is it acceptable for me to take a look at the code you used for evaluating single-cell data? Many thanks to your kindness!

Sincerely,
Tianyu

**Comment by RonenTalmonLab** [comment]
Your error message could arise in line 117 or line 123. Please make sure the input of the function satisfies the required datatype format. The variable tmp should not be the source of the issue since it is used as a collecting variable and it will be updated in the for loop.
